mod m0547_number_of_provinces;

mod m1011_capacity_to_ship_packages_within_d_days;

mod m1551_minimum_operations_to_make_array_equal;

mod m1664_ways_to_make_a_fair_array;

mod m1763_longest_nice_substring;
